spring:
  application:
    name: authentication
  webflux:
    static-path-pattern: ""
  web:
    resources:
      add-mappings: false
      static-locations: [ ]
      cache:
        period: 0
  jackson:
    property-naming-strategy: SNAKE_CASE
  main:
    web-application-type: reactive
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
server:
  port: ${SERVER_PORT:8080}
jwt:
  refresh-secret: ${REFRESH_SECRET}
  access-secret: ${ACCESS_SECRET}
  access-token-expiration: ${ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION}
logging:
  level:
    org.springframework.r2dbc.core: ${DATABASE_LOG_LEVEL:DEBUG}
    io.r2dbc.spi: ${DATABASE_LOG_LEVEL:DEBUG}
    org.springframework.security: ${SECURITY_LOG_LEVEL:DEBUG}
    org.springframework.web: ${WEB_LOG_LEVEL:DEBUG}
